### ISSUE TITLE
Refactor to handle statewide court site search

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/court-scraper#29]
Refactor Runner and SitesMeta/sites_meta.csv to handle a single court site where all counties can be searched, as is the case for [Arkansas](https://caseinfo.arcourts.gov/cconnect/PROD/public/ck_public_qry_main.cp_main_idx)

**Comment by ryanelittle** [comment]
I propose that the existing design is sufficient. Treating every county as its own system is the best practice because it will reduce confusion among users and reflect similar situations where a supported platform is used across multiple jurisdictions that will each have their own state_countyname. To provide support for scraping all court data in one state, we should identify them as state_statewide and factor statewide platforms to handle this as an option.

**Comment by zstumgoren** [comment]
@ryanelittle Works for me. We can always revisit this in the future if statewide queries become a thing end users are requesting.
