### ISSUE TITLE
Add San Mateo County Odyssey Site

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/court-scraper#46]
Santa Mateo County [court site](https://odyportal-ext.sanmateocourt.org/portal-external) appears to use Tyler Tech/Odyssey platform.

It's not password protected but may be using Captchas.

We should add the site to [sites_meta.csv](https://github.com/biglocalnews/court-scraper/blob/master/court_scraper/data/sites_meta.csv) and test with the CLI runner.

Possible we may need to refactor [OdysseySite](https://github.com/biglocalnews/court-scraper/blob/master/court_scraper/platforms/odyssey_site/site.py) to handle Captchas.

**Comment by DiPierro** [comment]
I've been looking at this the past few days. To scrape San Mateo County's court website, I agree that it will be necessary to refactor OdysseySite in the following ways:

* **Make login optional.** This might already be possible in the current interface, but some design changes could still be helpful. At present, if a public user logs into SMC, they lose the ability to search for records. (It appears that the county uses its login to manage more privileged users, such as court administrators, rather than the general public.) One potential design change would be adding a boolean column to sites_meta.csv indicating whether a website is password protected, and making this one of the parameters needed to initialize OdysseySite.
* **Handle Captchas.** The user must solve a ReCaptcha in order to search SMC records. One potential solution is to adapt the ReCaptcha strategy from the **wiscourts** scraper to SMC. A potential drawback to this solutions is that it relies (to my understanding) on using a paid service to solve Captchas. In the long run, it would be advantageous to find a free solution.

I [wrote some demo code](https://gist.github.com/DiPierro/34412116cb5e3b09c3cae33c148e5463) attempting to beat the ReCaptcha using only `requests`. This strategy initially worked very well -- and then abruptly stopped working several hours into development. I attempted to continue scraping by using sessions browsing, but this did not help. One possible solution, I think, would be to rotate proxies.

**Comment by ryanelittle** [comment]
The San Mateo website uses Google ReCaptcha V2. This version works by judging your browser on a score of 0 to 1. Zero is definitely a human and 1 is definitely a robot. It is possible to change enough settings in your chrome profile to trick the system, but I have found it very difficult to do so with a high rate of success. 

This version of Odyssey cannot be scraped with Requests because the browser must interact with the search page to generate links to case details pages. I experimented with trying to build payloads at the end of the URL in Fulton, but nothing I tried ever worked.

The [existing captcha library](https://github.com/biglocalnews/court-scraper/blob/master/court_scraper/captcha/recaptcha_v2.py) can handle this website. The paid service is inexpensive. In 9 months of scraping multiple sites with captchas, the Howard Center spent less than $5.

**Comment by zstumgoren** [comment]
@ryanelittle Thanks for the Captcha details. We should plan to integrate those into the OdysseySite class as part of a refactor with tests. We'll also need to make user/pass optional parameters when instantiating the class to handle scenarios such as SMC. @DiPierro For now, you should in theory be able to pass dummy values for the user/pass when using the existing class, and then just call the [search](https://github.com/biglocalnews/court-scraper/blob/master/court_scraper/platforms/odyssey_site/site.py#L31) method. But shout back here if for some reason that doesn't work with SMC.

**Comment by zstumgoren** [comment]
@DiPierro Actually, on closer inspect, `OdysseySite.earch` relies on driver set up that appears to currently be handled by login. I think if you need to get some scrapes going in the short-term, you'll need to subclass and rewire the code a little bit. Easiest path might be to override the `login` method to set up the driver but *not* attempt an actual login when the site is SMC. Hopefully that will get you unblocked if you need to start your scraping project before we can get to the refactor.

**Comment by DiPierro** [comment]
Wonderful, thank you both.

**Comment by DiPierro** [comment]
Some updates on my end. I've been using the excellent existing captcha library, but am still having a bit of trouble solving. Here's how far I've gotten:
* I've edited `captcha.py` with the appropriate `SITEKEY` and `APIKEY` from the paid service. When I run the scraper, I can see that the service is successfully filling the ReCaptcha text box with a code. 
* However, as far as I can see, there's no submit button for the ReCaptcha on the San Mateo County site. [This post](https://2captcha.com/2captcha-api#callback) suggests that when there's no submit button, it's necessary to use a callback function to submit the ReCaptcha form. I've used [this script](https://gist.github.com/2captcha/2ee70fa1130e756e1693a5d4be4d8c70) to try to find the callback function using the console in Google Chrome. I've also manually inspected the results returned by `___grecaptcha_cfg.clients[0]` in the console. In both cases, I haven't been able to find the callback function.

Have either of you encountered this before? Any tips or techniques you'd suggest? Thanks as always.
